In [2]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [3]:
df_data = pd.read_csv('exercise1_data.csv')

In [4]:
X = df_data[['X1','X2','X3','X4']].to_numpy()
Y = df_data['Y'].to_numpy()
Y = np.expand_dims(Y,axis=1)

In [5]:
#a
#What is the value of m?
print(X.shape[0])
#The value of m is 1000, therefore there are 1000 smaples

1000


In [6]:
print(X)

[[ 1.13628767  0.67075584 -0.31658534 -1.75585788]
 [ 1.85603065  1.93540733 -0.48997094 -0.38728799]
 [-0.85757989 -0.79313091 -1.29775941  1.47715056]
 ...
 [ 0.46581094  0.73576916 -0.29699876 -0.36531577]
 [-0.12599579  2.23115351  0.27964412 -0.65317185]
 [-1.26156445  0.84245211 -0.08320848  0.01189734]]
